### ISSUE TITLE
Improve SequentialTasksExecutionStressTest

### ISSUE THREAD

**Issue by adam-enko** [Kotlin/dokka#3723]
Currently [SequentialTasksExecutionStressTest](https://github.com/Kotlin/dokka/blob/f5d7f60b174d60c2d58e21279ba86d6eb68546d6/dokka-integration-tests/gradle/src/testTemplateProjectTasksExecutionStress/kotlin/SequentialTasksExecutionStressTest.kt#L21) runs on every commit.

It is slow (~15 mins, much longer than the next slowest integration test, which takes ~6 mins).

It doesn't accurately measure performance, only whether memory is exhausted. It would be nice to have some sort of continuous monitoring of memory usage in a more fine-grained approach. that could be alerted on. Efforts on this are ongoing in the Kotlin team, but there is no solution yet. One interim option would be reporting metrics to TeamCity, and creating a custom graph.

Using Gradle to run Dokka Generator is convenient, but is most likely not necessary. Using Gradle introduces another layer that is not relevant for the purpose of testing Dokka Generator. Testing in this way also becomes less relevant when DGP will use the Worker API. Finally, if DGP is moved into the Kotlin repo, the performance testing of Dokka Generator should stay in the Dokka repo.

### Tasks

- [ ] Improve the speed: only test 50 iterations, instead of 100.
- [ ] Reduce the times it is run. Only run SequentialTasksExecutionStressTest on master branch.
- [ ] Reimplement SequentialTasksExecutionStressTest as a macro performance test.
